-- Hytale Server Logs - Persistent storage for game server console logs
-- Stores logs from Hytale game servers for historical retrieval and persistence

CREATE TABLE hytale_server_logs (
    id BIGSERIAL PRIMARY KEY,
    "serverUuid" TEXT NOT NULL,
    "accountId" VARCHAR(255) NOT NULL,
    "logLine" TEXT NOT NULL,
    "logTimestamp" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    -- Indexes for common queries
    CONSTRAINT fk_server_uuid FOREIGN KEY ("serverUuid") 
        REFERENCES servers(uuid) ON DELETE CASCADE
);

-- Create indexes for efficient log retrieval
CREATE INDEX idx_hytale_server_logs_server_uuid ON hytale_server_logs("serverUuid" DESC);
CREATE INDEX idx_hytale_server_logs_created_at ON hytale_server_logs("createdAt" DESC);
CREATE INDEX idx_hytale_server_logs_server_created ON hytale_server_logs("serverUuid" DESC, "createdAt" DESC);
CREATE INDEX idx_hytale_server_logs_account_id ON hytale_server_logs("accountId");

-- Create a table to track log persistence state (last synced timestamp)
CREATE TABLE hytale_log_sync_state (
    id SERIAL PRIMARY KEY,
    "serverUuid" TEXT NOT NULL UNIQUE,
    "lastSyncTime" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "lastLineId" BIGINT DEFAULT 0,
    "syncStatus" VARCHAR(50) DEFAULT 'pending', -- pending, syncing, success, failed
    "errorMessage" TEXT,
    "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_sync_server_uuid FOREIGN KEY ("serverUuid")
        REFERENCES servers(uuid) ON DELETE CASCADE
);

-- Create index for sync state queries
CREATE INDEX idx_hytale_log_sync_state_server_uuid ON hytale_log_sync_state("serverUuid");
CREATE INDEX idx_hytale_log_sync_state_status ON hytale_log_sync_state("syncStatus");

-- Add comment for documentation
COMMENT ON TABLE hytale_server_logs IS 'Stores persistent console output logs from Hytale game servers. Allows historical log retrieval and persistence across Panel page refreshes.';
COMMENT ON COLUMN hytale_server_logs."logTimestamp" IS 'Timestamp when the log line was generated by the game server';
COMMENT ON TABLE hytale_log_sync_state IS 'Tracks synchronization state between Hytale logs and local persistent storage.';
