-- Hytale Server Logs - Persistent storage for game server console logs
-- Stores logs from Hytale game servers for historical retrieval and persistence

CREATE TABLE hytale_server_logs (
    id BIGSERIAL PRIMARY KEY,
    server_uuid TEXT NOT NULL,
    account_id VARCHAR(255) NOT NULL,
    log_line TEXT NOT NULL,
    log_timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    -- Indexes for common queries
    CONSTRAINT fk_server_uuid FOREIGN KEY (server_uuid) 
        REFERENCES servers(uuid) ON DELETE CASCADE
);

-- Create indexes for efficient log retrieval
CREATE INDEX idx_hytale_server_logs_server_uuid ON hytale_server_logs(server_uuid DESC);
CREATE INDEX idx_hytale_server_logs_created_at ON hytale_server_logs(created_at DESC);
CREATE INDEX idx_hytale_server_logs_server_created ON hytale_server_logs(server_uuid DESC, created_at DESC);
CREATE INDEX idx_hytale_server_logs_account_id ON hytale_server_logs(account_id);

-- Create a table to track log persistence state (last synced timestamp)
CREATE TABLE hytale_log_sync_state (
    id SERIAL PRIMARY KEY,
    server_uuid TEXT NOT NULL UNIQUE,
    last_sync_time TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    last_line_id BIGINT DEFAULT 0,
    sync_status VARCHAR(50) DEFAULT 'pending', -- pending, syncing, success, failed
    error_message TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_sync_server_uuid FOREIGN KEY (server_uuid)
        REFERENCES servers(uuid) ON DELETE CASCADE
);

-- Create index for sync state queries
CREATE INDEX idx_hytale_log_sync_state_server_uuid ON hytale_log_sync_state(server_uuid);
CREATE INDEX idx_hytale_log_sync_state_status ON hytale_log_sync_state(sync_status);

-- Add comment for documentation
COMMENT ON TABLE hytale_server_logs IS 'Stores persistent console output logs from Hytale game servers. Allows historical log retrieval and persistence across Panel page refreshes.';
COMMENT ON COLUMN hytale_server_logs.log_timestamp IS 'Timestamp when the log line was generated by the game server';
COMMENT ON TABLE hytale_log_sync_state IS 'Tracks synchronization state between Hytale logs and local persistent storage.';
